### ISSUE TITLE
What is the purpose of setting "encoder.layers" and how does it differ from "encoder.layer" ? 

### ISSUE THREAD

**Issue by WeiweiZhang1** [WoosukKwon/retraining-free-pruning#15]
https://github.com/WoosukKwon/retraining-free-pruning/blob/806ac5a6ff53b4978e5330d45a3de692493e4d0b/utils/arch.py#LL107C9-L107C36

**Comment by WeiweiZhang1** [comment]
Do not care about this problem, just found out that this is a useless line of code.

**Comment by AboveParadise** [comment]
Same question, thanks
