### ISSUE TITLE
Missing datasets file?

### ISSUE THREAD

**Issue by justlovebarbecue** [WoosukKwon/retraining-free-pruning#4]
Hi Woosuk!

Thanks for sharing your code! I tried to run the example script but got:

from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'

It looks like the 'datasets' file is missed? Could you please help with it?

Thanks!

**Comment by WoosukKwon** [comment]
Hi!
`datasets` is a Hugging Face library that contains the GLUE and SQUAD datasets. You can install it via `pip install datasets`. It is actually included in `requirements.txt`.

**Comment by justlovebarbecue** [comment]
Thanks for your fast reply!! Will try it and closing!
