### ISSUE TITLE
Real-time inference results

### ISSUE THREAD

**Issue by justlovebarbecue** [WoosukKwon/retraining-free-pruning#5]
Hi @WoosukKwon,

Thanks for your code and your help for my previous question. I have another question about the real-time inference speed.

Like shown in Fig.3 in paper, the efficiency has been improved. I am wondering if this figure is plotted using some python functions like "time.time()" to record the operation time consumption? or estimated by some calculation functions like "MAC" or "Latency" provided in this repo?

Thanks!

**Comment by WoosukKwon** [comment]
Hi @justlovebarbecue

Currently, the main script only produces pruning masks. To get the actual latency speedup, I applied the masks to the original model and remove the zero-ed parts. That is, I transferred the non-zero model weights to a new smaller dense model. Then I measured its end-to-end GPU latency using `GPUTimer` in https://github.com/WoosukKwon/retraining-free-pruning/blob/493e09ac7ae90b1b50d8cc46f62feafd10fb6bc9/utils/timer.py#L18.

Please let me know if you have further question.

**Comment by justlovebarbecue** [comment]
Thanks for your reply @WoosukKwon! I missed this part previously. One more question, could you please point out where is the function to load the smaller dense model? 

Thanks!

**Comment by justlovebarbecue** [comment]
I guess, the file generate_lut.py provides a function to load a customized model and test the real-time speed using "GPUTimer"? Am I right?

**Comment by WoosukKwon** [comment]
Yeah, please check out the code in `generate_lut.py`.
