### ISSUE TITLE
About the speedup performance of the code

### ISSUE THREAD

**Issue by CaffreyR** [WoosukKwon/retraining-free-pruning#7]
Hi @WoosukKwon , in your paper. You use the code `outputs = model(head_mask=head_mask, **batch)` to get the output. So model is the same model, we change the `head_mask` to do pruning right? But does it really save time? I mean we actually do all the `forward` of bert  right? So we do not change the model architecture?  

Many thanks!

**Comment by WoosukKwon** [comment]
Yes, the output of this framework is a sparse mask, and the framework does not change the model architecture. In our experiments, we created a new small and dense BERT model based on the obtained mask's sparse patterns and values. This way, we could get the real latency speedup and memory saving.
